version: '3'
services:
  api:
    restart: always
    image: toreanjoel/leafnode:latest
    build: 
      context: ./
      dockerfile: ./docker/API/Dockerfile
    environment:
      - PORT=5000
      - APP_DATA=DATA
    ports:
      - "3000:5000"
    volumes:
      - ./DATA:/app/DATA
