version: '3'
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=leafnode_db_test
  api:
    restart: always
    image: toreanjoel/leafnode:latest
    build: 
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - PORT=5000
      - DB_HOSTNAME=localhost
      - DB_NAME=leafnode_db_test
      - DB_USER=postgres
      - DB_PASS=postgres
      - APP_DATA=DATA
    ports:
      - "3000:5000"
    depends_on:
      - db
