version: '3.7'
services:
  db:
    container_name: leafnode_db
    restart: always
    image: postgres
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    env_file:
      - db.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "3001:5432"
  app:
    container_name: leafnode_app
    restart: always
    platform: linux/arm64
    image: toreanjoel/leafnode:latest
    build: 
      context: ./
      dockerfile: ./Dockerfile
    env_file:
      - app.env
    ports:
      - "3000:5000"
    depends_on:
      - db
volumes:
  pgdata:
