version: '3.8'
services:
  db:
    restart: always
    image: postgres:15
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    env_file:
      - db.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "3001:5432"
  app:
    # TODO: change this to be the image and not directory
    restart: always
    build: 
      context: ./
      dockerfile: ./Dockerfile
    env_file:
      - app.env
    depends_on:
      - db
    expose:
      - 4000
    ports:
      - "4000:4000"
    command:
      - /bin/sh
      - -c
      - |
        # mix deps.clean --all
        mix deps.get
        mix ecto.create
        mix ecto.migrate
        mix phx.server
volumes:
  pgdata:
